[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip', 'gcc', 'pkg-config', 'libGL', 'glib', 'opencv4', 'ffmpeg']

[phases.install]
cmds = ['python3.9 -m pip install -r requirements.txt']

[start]
cmd = 'python manage.py runserver 0.0.0.0:8000'
